# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 742c164aae94cb67ec8d57952d5b55d8afe9cc49f42ba97f0e7b3ca7b061873cac91e4471a6ea0b94daa554898091573293edfdd8632819310bbead8e6f20fbd

test:
  secret_key_base: c2a3d2dcfe5644560302388c18c45044d466e6040001c1b48299b602c05bd3683ac34da707b7b633bf15267a967212c93036f7a81194dca065a1cc75170848eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
